# Generated by Django 3.2.5 on 2021-07-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='NotebookProduct',
        ),
        migrations.RenameModel(
            old_name='SmartPhone',
            new_name='SmartPhoneProduct',
        ),
    ]
